# Generated by Django 3.2.4 on 2021-06-10 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('header', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('str', models.PositiveSmallIntegerField()),
                ('dex', models.PositiveSmallIntegerField()),
                ('con', models.PositiveSmallIntegerField()),
                ('int', models.PositiveSmallIntegerField()),
                ('cha', models.PositiveSmallIntegerField()),
                ('hit_point_max', models.PositiveSmallIntegerField()),
                ('hit_points', models.SmallIntegerField()),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharacterManager.background')),
            ],
        ),
        migrations.CreateModel(
            name='ClassAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('level_1', models.TextField()),
                ('level_2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pronouns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('subject_pronoun', models.CharField(max_length=10)),
                ('object_pronoun', models.CharField(max_length=10)),
                ('possessive_adj', models.CharField(max_length=10)),
                ('possessive_pronoun', models.CharField(max_length=10)),
                ('reflexive_pronoun', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('psychic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('header', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'Novice'), (1, 'Pro'), (2, 'Veteran'), (3, 'Master'), (4, 'Super')], default=1)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CharacterManager.character')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CharacterManager.skill')),
            ],
        ),
        migrations.CreateModel(
            name='FocusLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CharacterManager.character')),
                ('focus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CharacterManager.focus')),
            ],
        ),
        migrations.CreateModel(
            name='CharClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abilities', models.ManyToManyField(to='CharacterManager.ClassAbility')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='char_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharacterManager.charclass'),
        ),
        migrations.AddField(
            model_name='character',
            name='foci',
            field=models.ManyToManyField(through='CharacterManager.FocusLevel', to='CharacterManager.Focus'),
        ),
        migrations.AddField(
            model_name='character',
            name='pronouns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharacterManager.pronouns'),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(through='CharacterManager.SkillLevel', to='CharacterManager.Skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharacterManager.species'),
        ),
    ]
