# Generated by Django 3.2.4 on 2021-06-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharacterManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pronouns',
            name='name',
        ),
        migrations.AlterField(
            model_name='skilllevel',
            name='level',
            field=models.IntegerField(choices=[(0, 'Novice'), (1, 'Competent'), (2, 'Veteran'), (3, 'Master'), (4, 'Elite')], default=1),
        ),
    ]
