# Generated by Django 3.2.4 on 2021-06-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharacterManager', '0002_auto_20210610_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronouns',
            name='gender_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
