# Generated by Django 3.2.4 on 2021-06-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.PositiveSmallIntegerField()),
                ('dex', models.PositiveSmallIntegerField()),
                ('con', models.PositiveSmallIntegerField()),
                ('int', models.PositiveSmallIntegerField()),
                ('cha', models.PositiveSmallIntegerField()),
                ('hit_point_max', models.PositiveSmallIntegerField()),
                ('hit_points', models.SmallIntegerField()),
            ],
        ),
    ]
