# Generated by Django 3.2.4 on 2021-06-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0002_auto_20210615_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='wisdom',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='charisma',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='constitution',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='current_hit_points',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='dexterity',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='hit_point_max',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='intelligence',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='strength',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
