# Generated by Django 3.2.4 on 2021-06-17 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0003_auto_20210615_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='character',
            name='faction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GameApp.faction'),
        ),
    ]
