# Generated by Django 3.2.4 on 2021-06-18 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0007_auto_20210617_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pronouns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(default='non-binary', max_length=50)),
                ('subject_pronoun', models.CharField(default='they', max_length=10)),
                ('object_pronoun', models.CharField(default='them', max_length=10)),
                ('possessive_adj', models.CharField(default='their', max_length=10)),
                ('possessive_pronoun', models.CharField(default='theirs', max_length=10)),
                ('reflexive_pronoun', models.CharField(default='themself', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='pronouns',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_pronouns', to='GameApp.pronouns'),
        ),
    ]
