# Generated by Django 3.2.4 on 2021-06-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0009_auto_20210622_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
