# Generated by Django 3.2.4 on 2021-07-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0012_alter_character_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
