# Generated by Django 3.2.4 on 2021-07-02 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0013_alter_character_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='current_hit_points',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='hit_point_max',
        ),
    ]
