# Generated by Django 3.2.4 on 2021-07-06 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0017_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsionicDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='character_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='current_hit_points',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='max_hit_points',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='psychic_effort',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'basic competency'), (1, 'experienced professional'), (2, 'respected veteran expert'), (3, 'mastery, best on the planet'), (4, 'superlative expertise, best in the sector')], default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameApp.skill')),
            ],
        ),
        migrations.CreateModel(
            name='PsionicTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameApp.psionicdiscipline')),
            ],
        ),
        migrations.CreateModel(
            name='PsionicDisciplineLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameApp.psionicdiscipline')),
            ],
        ),
    ]
