# Generated by Django 3.2.4 on 2021-07-06 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0018_auto_20210706_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('heading', models.TextField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='psionic_abilities',
            field=models.ManyToManyField(to='GameApp.PsionicTechnique'),
        ),
        migrations.AddField(
            model_name='character',
            name='psionic_disciplines',
            field=models.ManyToManyField(through='GameApp.PsionicDisciplineLevel', to='GameApp.PsionicDiscipline'),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(related_name='character_skills', through='GameApp.SkillLevel', to='GameApp.Skill'),
        ),
        migrations.AddField(
            model_name='psionicdisciplinelevel',
            name='character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GameApp.character'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skilllevel',
            name='character',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='GameApp.character'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FocusLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')], default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameApp.character')),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameApp.focus')),
            ],
        ),
        migrations.CreateModel(
            name='FocusAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')])),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameApp.focus')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='foci',
            field=models.ManyToManyField(related_name='character_foci', through='GameApp.FocusLevel', to='GameApp.Focus'),
        ),
    ]
