# Generated by Django 3.2.4 on 2021-07-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0019_auto_20210706_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='foci',
            field=models.ManyToManyField(blank=True, null=True, related_name='character_foci', through='GameApp.FocusLevel', to='GameApp.Focus'),
        ),
        migrations.AlterField(
            model_name='character',
            name='psionic_abilities',
            field=models.ManyToManyField(blank=True, null=True, to='GameApp.PsionicTechnique'),
        ),
        migrations.AlterField(
            model_name='character',
            name='psionic_disciplines',
            field=models.ManyToManyField(blank=True, null=True, through='GameApp.PsionicDisciplineLevel', to='GameApp.PsionicDiscipline'),
        ),
    ]
