# Generated by Django 3.2.4 on 2021-07-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0020_auto_20210706_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='foci',
            field=models.ManyToManyField(related_name='character_foci', through='GameApp.FocusLevel', to='GameApp.Focus'),
        ),
        migrations.AlterField(
            model_name='character',
            name='psionic_abilities',
            field=models.ManyToManyField(to='GameApp.PsionicTechnique'),
        ),
        migrations.AlterField(
            model_name='character',
            name='psionic_disciplines',
            field=models.ManyToManyField(through='GameApp.PsionicDisciplineLevel', to='GameApp.PsionicDiscipline'),
        ),
    ]
