# Generated by Django 3.2.4 on 2021-07-06 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0021_auto_20210706_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_classes', to='GameApp.characterclass'),
        ),
    ]
